sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f -t ccgorman/docker-kubernetes-frontend-app Dockerfile.dev .

script:
  - docker run -e CI=true ccgorman/docker-kubernetes-frontend-app npm run test
